# -*- coding: utf-8 -*-
# Generated by Django 2.0.2 on 2018-02-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.IntegerField(default=0)),
                ("log", models.CharField(blank=True, default="", max_length=10000)),
            ],
        ),
    ]
