# -*- coding: utf-8 -*-
# Generated by Django 2.0.2 on 2018-02-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("woodcutter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelog",
            name="supply",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
