# -*- coding: utf-8 -*-
# Generated by Django 2.0.2 on 2018-02-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("woodcutter", "0002_gamelog_supply"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("single_name", models.CharField(max_length=30)),
                ("multi_name", models.CharField(max_length=30)),
                ("phrase_name", models.CharField(max_length=30)),
                ("cost", models.IntegerField()),
                ("color", models.CharField(max_length=8)),
                ("border_color", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="ExceptionData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.IntegerField(blank=True)),
                ("destination", models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="PredData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regex", models.CharField(max_length=150)),
                ("source", models.IntegerField(blank=True)),
                ("destination", models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(model_name="gamelog", name="id",),
        migrations.AlterField(
            model_name="gamelog",
            name="game_id",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="exceptiondata",
            name="root_pred",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="woodcutter.PredData",
                verbose_name="root Pred",
            ),
        ),
        migrations.AddField(
            model_name="exceptiondata",
            name="target_cards",
            field=models.ManyToManyField(
                to="woodcutter.CardData", verbose_name="target Cards"
            ),
        ),
        migrations.AddField(
            model_name="exceptiondata",
            name="target_preds",
            field=models.ManyToManyField(
                related_name="_exceptiondata_target_preds_+",
                to="woodcutter.PredData",
                verbose_name="target Preds",
            ),
        ),
        migrations.AddField(
            model_name="carddata",
            name="exceptions",
            field=models.ManyToManyField(
                to="woodcutter.ExceptionData", verbose_name="exceptions"
            ),
        ),
    ]
