# -*- coding: utf-8 -*-
# Generated by Django 2.0 on 2018-02-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("woodcutter", "0004_auto_20180213_1105"),
    ]

    operations = [
        migrations.AlterModelOptions(name="carddata", options={"ordering": ["id"]},),
        migrations.AlterModelOptions(name="preddata", options={"ordering": ["id"]},),
        migrations.RemoveField(model_name="exceptiondata", name="root_pred",),
        migrations.AddField(
            model_name="exceptiondata",
            name="root_preds",
            field=models.ManyToManyField(
                related_name="_exceptiondata_root_preds_+",
                to="woodcutter.PredData",
                verbose_name="root Preds",
            ),
        ),
        migrations.AlterField(
            model_name="carddata",
            name="exceptions",
            field=models.ManyToManyField(
                blank=True, to="woodcutter.ExceptionData", verbose_name="exceptions"
            ),
        ),
        migrations.AlterField(
            model_name="carddata",
            name="multi_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="carddata",
            name="phrase_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
