# -*- coding: utf-8 -*-
# Generated by Django 2.0 on 2018-02-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("woodcutter", "0005_auto_20180213_1557"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exceptiondata",
            name="root_preds",
            field=models.ManyToManyField(
                blank=True,
                related_name="_exceptiondata_root_preds_+",
                to="woodcutter.PredData",
                verbose_name="root Preds",
            ),
        ),
        migrations.AlterField(
            model_name="exceptiondata",
            name="target_cards",
            field=models.ManyToManyField(
                blank=True, to="woodcutter.CardData", verbose_name="target Cards"
            ),
        ),
        migrations.AlterField(
            model_name="exceptiondata",
            name="target_preds",
            field=models.ManyToManyField(
                blank=True,
                related_name="_exceptiondata_target_preds_+",
                to="woodcutter.PredData",
                verbose_name="target Preds",
            ),
        ),
    ]
