# Generated by Django 2.0.2 on 2018-02-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodcutter', '0008_auto_20180215_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='players',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
