# Generated by Django 2.0 on 2018-02-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodcutter', '0009_gamelog_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddata',
            name='supply_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='log',
            field=models.CharField(blank=True, default='', max_length=15000),
        ),
    ]
