# -*- coding: utf-8 -*-
# Generated by Django 2.0 on 2018-03-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("woodcutter", "0010_auto_20180221_2351"),
    ]

    operations = [
        migrations.RemoveField(model_name="exceptiondata", name="root_card",),
        migrations.RemoveField(model_name="exceptiondata", name="root_preds",),
        migrations.RemoveField(model_name="exceptiondata", name="target_cards",),
        migrations.RemoveField(model_name="exceptiondata", name="target_preds",),
        migrations.DeleteModel(name="CardData",),
        migrations.DeleteModel(name="ExceptionData",),
        migrations.DeleteModel(name="PredData",),
    ]
