# -*- coding: utf-8 -*-
# Generated by Django 2.0 on 2018-03-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("woodcutter", "0012_auto_20180318_2121"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelog", name="valid", field=models.BooleanField(default=True),
        ),
    ]
