# -*- coding: utf-8 -*-
# Generated by Django 2.0.2 on 2018-03-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("woodcutter", "0013_gamelog_valid"),
        ("woodcutter", "0012_auto_20180318_1919"),
    ]

    operations = []
