# -*- coding: utf-8 -*-
from .BaseCards import *
from .Intrigue import *
from .Seaside import *
from .Alchemy import *
from .Prosperity import *
from .Cornucopia import *
from .Hinterlands import *
from .DarkAges import *
from .Guilds import *
from .Adventures import *
from .Empires import *
from .Nocturne import *
from .Renaissance import *
from .Menagerie import *
from .Promos import *

correspondences = {
    "Curse": CURSE(),
    "Copper": COPPER(),
    "Silver": SILVER(),
    "Gold": GOLD(),
    "Estate": ESTATE(),
    "Duchy": DUCHY(),
    "Province": PROVINCE(),
    "Artisan": ARTISAN(),
    "Bandit": BANDIT(),
    "Bureaucrat": BUREAUCRAT(),
    "Cellar": CELLAR(),
    "Chapel": CHAPEL(),
    "Council Room": COUNCIL_ROOM(),
    "Festival": FESTIVAL(),
    "Gardens": GARDENS(),
    "Harbinger": HARBINGER(),
    "Laboratory": LABORATORY(),
    "Library": LIBRARY(),
    "Market": MARKET(),
    "Merchant": MERCHANT(),
    "Militia": MILITIA(),
    "Mine": MINE(),
    "Moat": MOAT(),
    "Moneylender": MONEYLENDER(),
    "Poacher": POACHER(),
    "Remodel": REMODEL(),
    "Sentry": SENTRY(),
    "Smithy": SMITHY(),
    "Throne Room": THRONE_ROOM(),
    "Vassal": VASSAL(),
    "Village": VILLAGE(),
    "Witch": WITCH(),
    "Workshop": WORKSHOP(),
    "Courtyard": COURTYARD(),
    "Conspirator": CONSPIRATOR(),
    "Courtier": COURTIER(),
    "Baron": BARON(),
    "Bridge": BRIDGE(),
    "Diplomat": DIPLOMAT(),
    "Duke": DUKE(),
    "Harem": HAREM(),
    "Nobles": NOBLES(),
    "Ironworks": IRONWORKS(),
    "Lurker": LURKER(),
    "Masquerade": MASQUERADE(),
    "Mill": MILL(),
    "Mining Village": MINING_VILLAGE(),
    "Minion": MINION(),
    "Patrol": PATROL(),
    "Pawn": PAWN(),
    "Replace": REPLACE(),
    "Secret Passage": SECRET_PASSAGE(),
    "Shanty Town": SHANTY_TOWN(),
    "Steward": STEWARD(),
    "Swindler": SWINDLER(),
    "Torturer": TORTURER(),
    "Trading Post": TRADING_POST(),
    "Upgrade": UPGRADE(),
    "Wishing Well": WISHING_WELL(),
    "Ambassador": AMBASSADOR(),
    "Bazaar": BAZAAR(),
    "Caravan": CARAVAN(),
    "Cutpurse": CUTPURSE(),
    "Embargo": EMBARGO(),
    "Explorer": EXPLORER(),
    "Fishing Village": FISHING_VILLAGE(),
    "Ghost Ship": GHOST_SHIP(),
    "Haven": HAVEN(),
    "Island": ISLAND(),
    "Lighthouse": LIGHTHOUSE(),
    "Lookout": LOOKOUT(),
    "Merchant Ship": MERCHANT_SHIP(),
    "Native Village": NATIVE_VILLAGE(),
    "Navigator": NAVIGATOR(),
    "Outpost": OUTPOST(),
    "Pearl Diver": PEARL_DIVER(),
    "Pirate Ship": PIRATE_SHIP(),
    "Salvager": SALVAGER(),
    "Sea Hag": SEA_HAG(),
    "Smugglers": SMUGGLERS(),
    "Tactician": TACTICIAN(),
    "Treasure Map": TREASURE_MAP(),
    "Treasury": TREASURY(),
    "Warehouse": WAREHOUSE(),
    "Wharf": WHARF(),
    "Alchemist": ALCHEMIST(),
    "Apothecary": APOTHECARY(),
    "Apprentice": APPRENTICE(),
    "Familiar": FAMILIAR(),
    "Golem": GOLEM(),
    "Herbalist": HERBALIST(),
    "Philosophers Stone": PHILOSOPHERS_STONE(),
    "Possession": POSSESSION(),
    "Potion": POTION(),
    "Scrying Pool": SCRYING_POOL(),
    "Transmute": TRANSMUTE(),
    "University": UNIVERSITY(),
    "Vineyard": VINEYARD(),
    "Bank": BANK(),
    "Bishop": BISHOP(),
    "Colony": COLONY(),
    "Contraband": CONTRABAND(),
    "Counting House": COUNTING_HOUSE(),
    "City": CITY(),
    "Expand": EXPAND(),
    "Forge": FORGE(),
    "Grand Market": GRAND_MARKET(),
    "Goons": GOONS(),
    "Hoard": HOARD(),
    "Kings Court": KINGS_COURT(),
    "Loan": LOAN(),
    "Mint": MINT(),
    "Monument": MONUMENT(),
    "Mountebank": MOUNTEBANK(),
    "Peddler": PEDDLER(),
    "Platinum": PLATINUM(),
    "Quarry": QUARRY(),
    "Rabble": RABBLE(),
    "Royal Seal": ROYAL_SEAL(),
    "Talisman": TALISMAN(),
    "Trade Route": TRADE_ROUTE(),
    "Vault": VAULT(),
    "Venture": VENTURE(),
    "Watchtower": WATCHTOWER(),
    "Workers Village": WORKERS_VILLAGE(),
    "Bag Of Gold": BAG_OF_GOLD(),
    "Diadem": DIADEM(),
    "Fairgrounds": FAIRGROUNDS(),
    "Farming Village": FARMING_VILLAGE(),
    "Followers": FOLLOWERS(),
    "Fortune Teller": FORTUNE_TELLER(),
    "Hamlet": HAMLET(),
    "Harvest": HARVEST(),
    "Horse Traders": HORSE_TRADERS(),
    "Horn Of Plenty": HORN_OF_PLENTY(),
    "Hunting Party": HUNTING_PARTY(),
    "Jester": JESTER(),
    "Menagerie": MENAGERIE(),
    "Princess": PRINCESS(),
    "Remake": REMAKE(),
    "Tournament": TOURNAMENT(),
    "Trusty Steed": TRUSTY_STEED(),
    "Young Witch": YOUNG_WITCH(),
    "Border Village": BORDER_VILLAGE(),
    "Cache": CACHE(),
    "Cartographer": CARTOGRAPHER(),
    "Crossroads": CROSSROADS(),
    "Develop": DEVELOP(),
    "Duchess": DUCHESS(),
    "Embassy": EMBASSY(),
    "Farmland": FARMLAND(),
    "Fools Gold": FOOLS_GOLD(),
    "Haggler": HAGGLER(),
    "Highway": HIGHWAY(),
    "Ill Gotten Gains": ILL_GOTTEN_GAINS(),
    "Inn": INN(),
    "Jack Of All Trades": JACK_OF_ALL_TRADES(),
    "Mandarin": MANDARIN(),
    "Noble Brigand": NOBLE_BRIGAND(),
    "Nomad Camp": NOMAD_CAMP(),
    "Oasis": OASIS(),
    "Oracle": ORACLE(),
    "Margrave": MARGRAVE(),
    "Scheme": SCHEME(),
    "Silk Road": SILK_ROAD(),
    "Spice Merchant": SPICE_MERCHANT(),
    "Stables": STABLES(),
    "Trader": TRADER(),
    "Tunnel": TUNNEL(),
    "Ruin Pile": RUINS(),
    "Knights": KNIGHTS(),
    "Abandoned Mine": ABANDONED_MINE(),
    "Altar": ALTAR(),
    "Armory": ARMORY(),
    "Band Of Misfits": BAND_OF_MISFITS(),
    "Bandit Camp": BANDIT_CAMP(),
    "Beggar": BEGGAR(),
    "Catacombs": CATACOMBS(),
    "Count": COUNT(),
    "Counterfeit": COUNTERFEIT(),
    "Cultist": CULTIST(),
    "Dame Anna": DAME_ANNA(),
    "Dame Josephine": DAME_JOSEPHINE(),
    "Dame Molly": DAME_MOLLY(),
    "Dame Natalie": DAME_NATALIE(),
    "Dame Sylvia": DAME_SYLVIA(),
    "Death Cart": DEATH_CART(),
    "Feodum": FEODUM(),
    "Forager": FORAGER(),
    "Fortress": FORTRESS(),
    "Graverobber": GRAVEROBBER(),
    "Hermit": HERMIT(),
    "Hovel": HOVEL(),
    "Hunting Grounds": HUNTING_GROUNDS(),
    "Ironmonger": IRONMONGER(),
    "Junk Dealer": JUNK_DEALER(),
    "Madman": MADMAN(),
    "Market Square": MARKET_SQUARE(),
    "Marauder": MARAUDER(),
    "Mercenary": MERCENARY(),
    "Mystic": MYSTIC(),
    "Necropolis": NECROPOLIS(),
    "Overgrown Estate": OVERGROWN_ESTATE(),
    "Pillage": PILLAGE(),
    "Poor House": POOR_HOUSE(),
    "Procession": PROCESSION(),
    "Rats": RATS(),
    "Rebuild": REBUILD(),
    "Rogue": ROGUE(),
    "Ruined Library": RUINED_LIBRARY(),
    "Ruined Market": RUINED_MARKET(),
    "Ruined Village": RUINED_VILLAGE(),
    "Sage": SAGE(),
    "Scavenger": SCAVENGER(),
    "Sir Bailey": SIR_BAILEY(),
    "Sir Destry": SIR_DESTRY(),
    "Sir Martin": SIR_MARTIN(),
    "Sir Michael": SIR_MICHAEL(),
    "Sir Vander": SIR_VANDER(),
    "Spoils": SPOILS(),
    "Storeroom": STOREROOM(),
    "Squire": SQUIRE(),
    "Survivors": SURVIVORS(),
    "Urchin": URCHIN(),
    "Vagrant": VAGRANT(),
    "Wandering Minstrel": WANDERING_MINSTREL(),
    "Advisor": ADVISOR(),
    "Baker": BAKER(),
    "Butcher": BUTCHER(),
    "Candlestick Maker": CANDLESTICK_MAKER(),
    "Doctor": DOCTOR(),
    "Herald": HERALD(),
    "Journeyman": JOURNEYMAN(),
    "Masterpiece": MASTERPIECE(),
    "Merchant Guild": MERCHANT_GUILD(),
    "Plaza": PLAZA(),
    "Taxman": TAXMAN(),
    "Soothsayer": SOOTHSAYER(),
    "Stonemason": STONEMASON(),
    "Alms": ALMS(),
    "Amulet": AMULET(),
    "Artificer": ARTIFICER(),
    "Ball": BALL(),
    "Bonfire": BONFIRE(),
    "Borrow": BORROW(),
    "Bridge Troll": BRIDGE_TROLL(),
    "Caravan Guard": CARAVAN_GUARD(),
    "Champion": CHAMPION(),
    "Coin Of The Realm": COIN_OF_THE_REALM(),
    "Disciple": DISCIPLE(),
    "Distant Lands": DISTANT_LANDS(),
    "Dungeon": DUNGEON(),
    "Duplicate": DUPLICATE(),
    "Expedition": EXPEDITION(),
    "Ferry": FERRY(),
    "Fugitive": FUGITIVE(),
    "Gear": GEAR(),
    "Giant": GIANT(),
    "Guide": GUIDE(),
    "Haunted Woods": HAUNTED_WOODS(),
    "Hero": HERO(),
    "Hireling": HIRELING(),
    "Inheritance": INHERITANCE(),
    "Lost Arts": LOST_ARTS(),
    "Lost City": LOST_CITY(),
    "Magpie": MAGPIE(),
    "Messenger": MESSENGER(),
    "Miser": MISER(),
    "Mission": MISSION(),
    "Pathfinding": PATHFINDING(),
    "Page": PAGE(),
    "Peasant": PEASANT(),
    "Pilgrimage": PILGRIMAGE(),
    "Plan": PLAN(),
    "Port": PORT(),
    "Quest": QUEST(),
    "Ranger": RANGER(),
    "Raid": RAID(),
    "Ratcatcher": RATCATCHER(),
    "Raze": RAZE(),
    "Relic": RELIC(),
    "Royal Carriage": ROYAL_CARRIAGE(),
    "Save": SAVE(),
    "Scouting Party": SCOUTING_PARTY(),
    "Seaway": SEAWAY(),
    "Soldier": SOLDIER(),
    "Storyteller": STORYTELLER(),
    "Swamp Hag": SWAMP_HAG(),
    "Teacher": TEACHER(),
    "Travelling Fair": TRAVELLING_FAIR(),
    "Trade": TRADE(),
    "Training": TRAINING(),
    "Transmogrify": TRANSMOGRIFY(),
    "Treasure Trove": TREASURE_TROVE(),
    "Treasure Hunter": TREASURE_HUNTER(),
    "Warrior": WARRIOR(),
    "Wine Merchant": WINE_MERCHANT(),
    "Encampment": ENCAMPMENT(),
    "Plunder": PLUNDER(),
    "Patrician": PATRICIAN(),
    "Emporium": EMPORIUM(),
    "Settlers": SETTLERS(),
    "Bustling Village": BUSTLING_VILLAGE(),
    "Catapult": CATAPULT(),
    "Rocks": ROCKS(),
    "Gladiator": GLADIATOR(),
    "Fortune": FORTUNE(),
    "Castles": CASTLES(),
    "Humble Castle": HUMBLE_CASTLE(),
    "Crumbling Castle": CRUMBLING_CASTLE(),
    "Small Castle": SMALL_CASTLE(),
    "Haunted Castle": HAUNTED_CASTLE(),
    "Opulent Castle": OPULENT_CASTLE(),
    "Sprawling Castle": SPRAWLING_CASTLE(),
    "Grand Castle": GRAND_CASTLE(),
    "Kings Castle": KINGS_CASTLE(),
    "Advance": ADVANCE(),
    "Annex": ANNEX(),
    "Archive": ARCHIVE(),
    "Aqueduct": AQUEDUCT(),
    "Arena": ARENA(),
    "Bandit Fort": BANDIT_FORT(),
    "Banquet": BANQUET(),
    "Basilica": BASILICA(),
    "Baths": BATHS(),
    "Battlefield": BATTLEFIELD(),
    "Capital": CAPITAL(),
    "Charm": CHARM(),
    "Chariot Race": CHARIOT_RACE(),
    "City Quarter": CITY_QUARTER(),
    "Colonnade": COLONNADE(),
    "Conquest": CONQUEST(),
    "Crown": CROWN(),
    "Delve": DELVE(),
    "Defiled Shrine": DEFILED_SHRINE(),
    "Dominate": DOMINATE(),
    "Donate": DONATE(),
    "Enchantress": ENCHANTRESS(),
    "Engineer": ENGINEER(),
    "Farmers Market": FARMERS_MARKET(),
    "Forum": FORUM(),
    "Fountain": FOUNTAIN(),
    "Groundskeeper": GROUNDSKEEPER(),
    "Keep": KEEP(),
    "Labyrinth": LABYRINTH(),
    "Legionary": LEGIONARY(),
    "Mountain Pass": MOUNTAIN_PASS(),
    "Museum": MUSEUM(),
    "Obelisk": OBELISK(),
    "Orchard": ORCHARD(),
    "Overlord": OVERLORD(),
    "Palace": PALACE(),
    "Ritual": RITUAL(),
    "Royal Blacksmith": ROYAL_BLACKSMITH(),
    "Sacrifice": SACRIFICE(),
    "Salt The Earth": SALT_THE_EARTH(),
    "Tax": TAX(),
    "Temple": TEMPLE(),
    "Tomb": TOMB(),
    "Tower": TOWER(),
    "Triumph": TRIUMPH(),
    "Triumphal Arch": TRIUMPHAL_ARCH(),
    "Villa": VILLA(),
    "Wall": WALL(),
    "Wolf Den": WOLF_DEN(),
    "Wedding": WEDDING(),
    "Wild Hunt": WILD_HUNT(),
    "Windfall": WINDFALL(),
    "The Earths Gift": THE_EARTHS_GIFT(),
    "The Fields Gift": THE_FIELDS_GIFT(),
    "The Flames Gift": THE_FLAMES_GIFT(),
    "The Forests Gift": THE_FORESTS_GIFT(),
    "The Moons Gift": THE_MOONS_GIFT(),
    "The Mountains Gift": THE_MOUNTAINS_GIFT(),
    "The Rivers Gift": THE_RIVERS_GIFT(),
    "The Seas Gift": THE_SEAS_GIFT(),
    "The Skys Gift": THE_SKYS_GIFT(),
    "The Suns Gift": THE_SUNS_GIFT(),
    "The Swamps Gift": THE_SWAMPS_GIFT(),
    "The Winds Gift": THE_WINDS_GIFT(),
    "Bad Omens": BAD_OMENS(),
    "Delusion": DELUSION(),
    "Envy": ENVY(),
    "Famine": FAMINE(),
    "Fear": FEAR(),
    "Greed": GREED(),
    "Haunting": HAUNTING(),
    "Locusts": LOCUSTS(),
    "Misery": MISERY(),
    "Plague": PLAGUE(),
    "Poverty": POVERTY(),
    "War": WAR(),
    "Miserable": MISERABLE(),
    "Twice Miserable": TWICE_MISERABLE(),
    "Envious": ENVIOUS(),
    "Deluded": DELUDED(),
    "Lost In The Woods": LOST_IN_THE_WOODS(),
    "Bard": BARD(),
    "Blessed Village": BLESSED_VILLAGE(),
    "Changeling": CHANGELING(),
    "Cemetery": CEMETERY(),
    "Cobbler": COBBLER(),
    "Conclave": CONCLAVE(),
    "Crypt": CRYPT(),
    "Cursed Village": CURSED_VILLAGE(),
    "Den Of Sin": DEN_OF_SIN(),
    "Devils Workshop": DEVILS_WORKSHOP(),
    "Druid": DRUID(),
    "Exorcist": EXORCIST(),
    "Faithful Hound": FAITHFUL_HOUND(),
    "Fool": FOOL(),
    "Ghost Town": GHOST_TOWN(),
    "Guardian": GUARDIAN(),
    "Idol": IDOL(),
    "Leprechaun": LEPRECHAUN(),
    "Monastery": MONASTERY(),
    "Necromancer": NECROMANCER(),
    "Night Watchman": NIGHT_WATCHMAN(),
    "Pixie": PIXIE(),
    "Pooka": POOKA(),
    "Raider": RAIDER(),
    "Sacred Grove": SACRED_GROVE(),
    "Secret Cave": SECRET_CAVE(),
    "Shepherd": SHEPHERD(),
    "Skulk": SKULK(),
    "Tormentor": TORMENTOR(),
    "Tragic Hero": TRAGIC_HERO(),
    "Tracker": TRACKER(),
    "Vampire": VAMPIRE(),
    "Werewolf": WEREWOLF(),
    "Cursed Gold": CURSED_GOLD(),
    "Goat": GOAT(),
    "Haunted Mirror": HAUNTED_MIRROR(),
    "Lucky Coin": LUCKY_COIN(),
    "Magic Lamp": MAGIC_LAMP(),
    "Pasture": PASTURE(),
    "Pouch": POUCH(),
    "Bat": BAT(),
    "Ghost": GHOST(),
    "Imp": IMP(),
    "Will O Wisp": WILL_O_WISP(),
    "Wish": WISH(),
    "Zombie Apprentice": ZOMBIE_APPRENTICE(),
    "Zombie Mason": ZOMBIE_MASON(),
    "Zombie Spy": ZOMBIE_SPY(),
    "Acting Troupe": ACTING_TROUPE(),
    "Border Guard": BORDER_GUARD(),
    "Cargo Ship": CARGO_SHIP(),
    "Ducat": DUCAT(),
    "Experiment": EXPERIMENT(),
    "Flag Bearer": FLAG_BEARER(),
    "Hideout": HIDEOUT(),
    "Inventor": INVENTOR(),
    "Improve": IMPROVE(),
    "Lackeys": LACKEYS(),
    "Mountain Village": MOUNTAIN_VILLAGE(),
    "Patron": PATRON(),
    "Priest": PRIEST(),
    "Research": RESEARCH(),
    "Silk Merchant": SILK_MERCHANT(),
    "Old Witch": OLD_WITCH(),
    "Recruiter": RECRUITER(),
    "Scepter": SCEPTER(),
    "Scholar": SCHOLAR(),
    "Sculptor": SCULPTOR(),
    "Seer": SEER(),
    "Spices": SPICES(),
    "Swashbuckler": SWASHBUCKLER(),
    "Treasurer": TREASURER(),
    "Villain": VILLAIN(),
    "Flag": FLAG(),
    "Horn": HORN(),
    "Key": KEY(),
    "Lantern": LANTERN(),
    "Treasure Chest": TREASURE_CHEST(),
    "Academy": ACADEMY(),
    "Barracks": BARRACKS(),
    "Canal": CANAL(),
    "Capitalism": CAPITALISM(),
    "Cathedral": CATHEDRAL(),
    "Citadel": CITADEL(),
    "City Gate": CITY_GATE(),
    "Crop Rotation": CROP_ROTATION(),
    "Exploration": EXPLORATION(),
    "Fair": FAIR(),
    "Fleet": FLEET(),
    "Guildhall": GUILDHALL(),
    "Innovation": INNOVATION(),
    "Pageant": PAGEANT(),
    "Piazza": PIAZZA(),
    "Road Network": ROAD_NETWORK(),
    "Sewers": SEWERS(),
    "Silos": SILOS(),
    "Sinister Plot": SINISTER_PLOT(),
    "Star Chart": STAR_CHART(),
    "Sauna": SAUNA(),
    "Avanto": AVANTO(),
    "Black Market": BLACK_MARKET(),
    "Envoy": ENVOY(),
    "Governor": GOVERNOR(),
    "Prince": PRINCE(),
    "Stash": STASH(),
    "Summon": SUMMON(),
    "Walled Village": WALLED_VILLAGE(),
    "Black Market Pile": BLACK_MARKET_DECK(),
    "Dismantle": DISMANTLE(),
    "Captain": CAPTAIN(),
    "Church": CHURCH(),
    "Black Cat": BLACK_CAT(),
    "Sleigh": SLEIGH(),
    "Supplies": SUPPLIES(),
    "Camel Train": CAMEL_TRAIN(),
    "Goatherd": GOATHERD(),
    "Scrap": SCRAP(),
    "Sheepdog": SHEEPDOG(),
    "Snowy Village": SNOWY_VILLAGE(),
    "Stockpile": STOCKPILE(),
    "Bounty Hunter": BOUNTY_HUNTER(),
    "Cardinal": CARDINAL(),
    "Cavalry": CAVALRY(),
    "Groom": GROOM(),
    "Hostelry": HOSTELRY(),
    "Village Green": VILLAGE_GREEN(),
    "Barge": BARGE(),
    "Coven": COVEN(),
    "Displace": DISPLACE(),
    "Falconer": FALCONER(),
    "Fisherman": FISHERMAN(),
    "Gatekeeper": GATEKEEPER(),
    "Hunting Lodge": HUNTING_LODGE(),
    "Kiln": KILN(),
    "Livery": LIVERY(),
    "Mastermind": MASTERMIND(),
    "Paddock": PADDOCK(),
    "Sanctuary": SANCTUARY(),
    "Destrier": DESTRIER(),
    "Wayfarer": WAYFARER(),
    "Animal Fair": ANIMAL_FAIR(),
    "Horse": HORSE(),
    "Way Of The Butterfly": WAY_OF_THE_BUTTERFLY(),
    "Way Of The Camel": WAY_OF_THE_CAMEL(),
    "Way Of The Chameleon": WAY_OF_THE_CHAMELEON(),
    "Way Of The Frog": WAY_OF_THE_FROG(),
    "Way Of The Goat": WAY_OF_THE_GOAT(),
    "Way Of The Horse": WAY_OF_THE_HORSE(),
    "Way Of The Mole": WAY_OF_THE_MOLE(),
    "Way Of The Monkey": WAY_OF_THE_MONKEY(),
    "Way Of The Mouse": WAY_OF_THE_MOUSE(),
    "Way Of The Mule": WAY_OF_THE_MULE(),
    "Way Of The Otter": WAY_OF_THE_OTTER(),
    "Way Of The Owl": WAY_OF_THE_OWL(),
    "Way Of The Ox": WAY_OF_THE_OX(),
    "Way Of The Pig": WAY_OF_THE_PIG(),
    "Way Of The Rat": WAY_OF_THE_RAT(),
    "Way Of The Seal": WAY_OF_THE_SEAL(),
    "Way Of The Sheep": WAY_OF_THE_SHEEP(),
    "Way Of The Squirrel": WAY_OF_THE_SQUIRREL(),
    "Way Of The Turtle": WAY_OF_THE_TURTLE(),
    "Way Of The Worm": WAY_OF_THE_WORM(),
    "Delay": DELAY(),
    "Desperation": DESPERATION(),
    "Gamble": GAMBLE(),
    "Pursue": PURSUE(),
    "Ride": RIDE(),
    "Toil": TOIL(),
    "Enhance": ENHANCE(),
    "March": MARCH(),
    "Transport": TRANSPORT(),
    "Banish": BANISH(),
    "Bargain": BARGAIN(),
    "Invest": INVEST(),
    "Seize The Day": SEIZE_THE_DAY(),
    "Commerce": COMMERCE(),
    "Demand": DEMAND(),
    "Stampede": STAMPEDE(),
    "Reap": REAP(),
    "Enclave": ENCLAVE(),
    "Alliance": ALLIANCE(),
    "Populate": POPULATE(),
}


def getCardInfo(card):
    if card in correspondences:
        return correspondences[card]
    else:
        return CardInfo()
