actionList = ['Artisan',
              'Bandit',
              'Bureaucrat',
              'Cellar',
              'Chapel',
              'Council Room',
              'Festival',
              'Harbinger',
              'Laboratory',
              'Library',
              'Market',
              'Merchant',
              'Militia',
              'Mine',
              'Moat',
              'Moneylender',
              'Poacher',
              'Remodel',
              'Sentry',
              'Smithy',
              'Throne Room',
              'Vassal',
              'Village',
              'Witch',
              'Workshop',
              'Courtyard',
              'Conspirator',
              'Courtier',
              'Baron',
              'Bridge',
              'Diplomat',
              'Nobles',
              'Ironworks',
              'Lurker',
              'Masquerade',
              'Mill',
              'Mining Village',
              'Minion',
              'Patrol',
              'Pawn',
              'Replace',
              'Secret Passage',
              'Shanty Town',
              'Steward',
              'Swindler',
              'Torturer',
              'Trading Post',
              'Upgrade',
              'Wishing Well',
              'Ambassador',
              'Bazaar',
              'Caravan',
              'Cutpurse',
              'Embargo',
              'Explorer',
              'Fishing Village',
              'Ghost Ship',
              'Haven',
              'Island',
              'Lighthouse',
              'Lookout',
              'Merchant Ship',
              'Native Village',
              'Navigator',
              'Outpost',
              'Pearl Diver',
              'Pirate Ship',
              'Salvager',
              'Sea Hag',
              'Smugglers',
              'Tactician',
              'Treasure Map',
              'Treasury',
              'Warehouse',
              'Wharf',
              'Alchemist',
              'Apothecary',
              'Apprentice',
              'Familiar',
              'Golem',
              'Herbalist',
              'Possession',
              'Scrying Pool',
              'Transmute',
              'University',
              'Bishop',
              'Counting House',
              'City',
              'Expand',
              'Forge',
              'Grand Market',
              'Goons',
              'King\'s Court',
              'Mint',
              'Monument',
              'Mountebank',
              'Peddler',
              'Rabble',
              'Trade Route',
              'Vault',
              'Watchtower',
              'Worker\'s Village',
              'Bag of Gold',
              'Farming Village',
              'Followers',
              'Fortune Teller',
              'Hamlet',
              'Harvest',
              'Horse Traders',
              'Hunting Party',
              'Jester',
              'Menagerie',
              'Princess',
              'Remake',
              'Tournament',
              'Trusty Steed',
              'Young Witch',
              'Border Village',
              'Cartographer',
              'Crossroads',
              'Develop',
              'Duchess',
              'Embassy',
              'Haggler',
              'Highway',
              'Inn',
              'Jack of All Trades',
              'Mandarin',
              'Noble Brigand',
              'Nomad Camp',
              'Oasis',
              'Oracle',
              'Margrave',
              'Scheme',
              'Spice Merchant',
              'Stables',
              'Trader',
              'Ruins',
              'Knights',
              'Abandoned Mine',
              'Altar',
              'Armory',
              'Band of Misfits',
              'Bandit Camp',
              'Beggar',
              'Catacombs',
              'Count',
              'Cultist',
              'Dame Anna',
              'Dame Josephine',
              'Dame Molly',
              'Dame Natalie',
              'Dame Sylvia',
              'Death Cart',
              'Forager',
              'Fortress',
              'Graverobber',
              'Hermit',
              'Hunting Grounds',
              'Ironmonger',
              'Junk Dealer',
              'Madman',
              'Market Square',
              'Marauder',
              'Mercenary',
              'Mystic',
              'Necropolis',
              'Pillage',
              'Poor House',
              'Procession',
              'Rats',
              'Rebuild',
              'Rogue',
              'Ruined Library',
              'Ruined Market',
              'Ruined Village',
              'Sage',
              'Scavenger',
              'Sir Bailey',
              'Sir Destry',
              'Sir Martin',
              'Sir Michael',
              'Sir Vander',
              'Storeroom',
              'Squire',
              'Survivors',
              'Urchin',
              'Vagrant',
              'Wandering Minstrel',
              'Advisor',
              'Baker',
              'Butcher',
              'Candlestick Maker',
              'Doctor',
              'Herald',
              'Journeyman',
              'Merchant Guild',
              'Plaza',
              'Taxman',
              'Soothsayer',
              'Stonemason',
              'Amulet',
              'Artificer',
              'Bridge Troll',
              'Caravan Guard',
              'Champion',
              'Disciple',
              'Distant Lands',
              'Dungeon',
              'Duplicate',
              'Fugitive',
              'Gear',
              'Giant',
              'Guide',
              'Haunted Woods',
              'Hero',
              'Hireling',
              'Lost City',
              'Magpie',
              'Messenger',
              'Miser',
              'Page',
              'Peasant',
              'Port',
              'Ranger',
              'Ratcatcher',
              'Raze',
              'Royal Carriage',
              'Soldier',
              'Storyteller',
              'Swamp Hag',
              'Teacher',
              'Transmogrify',
              'Treasure Hunter',
              'Warrior',
              'Wine Merchant',
              'Encampment',
              'Patrician',
              'Emporium',
              'Settlers',
              'Bustling Village',
              'Catapult',
              'Gladiator',
              'Small Castle',
              'Opulent Castle',
              'Archive',
              'Chariot Race',
              'City Quarter',
              'Crown',
              'Enchantress',
              'Engineer',
              'Farmers\' Market',
              'Forum',
              'Groundskeeper',
              'Legionary',
              'Overlord',
              'Royal Blacksmith',
              'Sacrifice',
              'Temple',
              'Villa',
              'Wild Hunt',
              'Bard',
              'Blessed Village',
              'Conclave',
              'Cursed Village',
              'Druid',
              'Faithful Hound',
              'Fool',
              'Leprechaun',
              'Necromancer',
              'Pixie',
              'Pooka',
              'Sacred Grove',
              'Secret Cave',
              'Shepherd',
              'Skulk',
              'Tormentor',
              'Tragic Hero',
              'Tracker',
              'Werewolf',
              'Imp',
              'Will-o\'-wisp',
              'Wish',
              'Zombie Apprentice',
              'Zombie Mason',
              'Zombie Spy',
              'Sauna',
              'Avanto',
              'Black Market',
              'Envoy',
              'Governor',
              'Prince',
              'Walled Village',
              'Dismantle']
victoryCards = ['Estate',
                'Duchy',
                'Province',
                'Gardens',
                'Duke',
                'Harem',
                'Nobles',
                'Mill',
                'Island',
                'Vineyard',
                'Colony',
                'Fairgrounds',
                'Farmland',
                'Silk Road',
                'Tunnel',
                'Dame Josephine',
                'Feodum',
                'Overgrown Estate',
                'Distant Lands',
                'Castles',
                'Humble Castle',
                'Crumbling Castle',
                'Small Castle',
                'Haunted Castle',
                'Opulent Castle',
                'Sprawling Castle',
                'Grand Castle',
                'King\'s Castle',
                'Cemetery',
                'Pasture']
treasures = ['Copper',
             'Silver',
             'Gold',
             'Harem',
             'Philosopher\'s Stone',
             'Potion',
             'Bank',
             'Contraband',
             'Hoard',
             'Loan',
             'Platinum',
             'Quarry',
             'Royal Seal',
             'Talisman',
             'Venture',
             'Diadem',
             'Horn of Plenty',
             'Cache',
             'Fool\'s Gold',
             'Ill-Gotten Gains',
             'Counterfeit',
             'Spoils',
             'Masterpiece',
             'Coin of the Realm',
             'Relic',
             'Treasure Trove',
             'Plunder',
             'Rocks',
             'Fortune',
             'Humble Castle',
             'Capital',
             'Charm',
             'Crown',
             'Idol',
             'Cursed Gold',
             'Goat',
             'Haunted Mirror',
             'Lucky Coin',
             'Magic Lamp',
             'Pasture',
             'Pouch',
             'Stash']
ZOMBIES = [450, 451, 452]
CASTLES = range(311, 320)
BOONHEX = [
           'The Earth\'s Gift',
           'The Field\'s Gift',
           'The Flame\'s Gift',
           'The Forest\'s Gift',
           'The Moon\'s Gift',
           'The Mountain\'s Gift',
           'The River\'s Gift',
           'The Sea\'s Gift',
           'The Sky\'s Gift',
           'The Sun\'s Gift',
           'The Swamp\'s Gift',
           'The Wind\'s Gift',
           'Hex Drawpile',
           'Hex Discardpile',
           'Bad Omens',
           'Delusion',
           'Envy',
           'Famine',
           'Fear',
           'Greed',
           'Haunting',
           'Locusts',
           'Misery',
           'Plague',
           'Poverty',
           'War',
           'Miserable',
           'Twice Miserable',
           'Envious',
           'Deluded']
pairs = [['Encampment', 'Plunder'],
         ['Patrician', 'Emporium'],
         ['Settlers', 'Bustling Village'],
         ['Catapult', 'Rocks'],
         ['Gladiator', 'Fortune'],
         ['Dame Anna', 'Dame Josephine', 'Dame Molly', 'Dame Natalie', 'Dame Sylvia'
          , 'Sir Bailey', 'Sir Destry', 'Sir Martin', 'Sir Michael', 'Sir Vander'],
         ['Ruined Library', 'Ruined Village', 'Abandoned Mine', 'Ruined Market', 'Survivors'],
         ['Sauna', 'Avanto']]
knights = ['Dame Anna', 'Dame Josephine', 'Dame Molly', 'Dame Natalie',
           'Dame Sylvia', 'Sir Bailey', 'Sir Destry', 'Sir Martin',
           'Sir Michael', 'Sir Vander']
landmarks = ['Bandit Fort', 'Fountain', 'Keep', 'Museum', 'Obelisk',
             'Orchard', 'Palace', 'Tower', 'Triumphal Arch',
             'Wall', 'Wolf Den']
events = ['']
pred_parse_order = list(range(26)) + [119] + list(range(26, 125))

DONT_LOAD = BOONHEX + landmarks + \
            ['Triumph', 'Annex', 'Donate', 'Advance',
             'Alms', 'Borrow', 'Quest', 'Save', 'Delve',
             'Scouting Party', 'Tax', 'Travelling Fair',
             'Banquet', 'Bonfire', 'Expedition', 'Ferry',
             'Plan', 'Mission', 'Pilgrimage', 'Ritual',
             'Salt the Earth', 'Wedding', 'Ball', 'Raid',
             'Seaway', 'Summon', 'Trade', 'Windfall',
             'Conquest', 'Lost Arts', 'Training',
             'Inheritance', 'Pathfinding', 'Dominate']

card_order = ['Argument',
              'nothing',
              'card',
              'Curse',
              'Ruined Library',
              'Ruined Market',
              'Ruined Village',
              'Survivors',
              'Abandoned Mine',
              'Overgrown Estate',
              'Necropolis',
              'Hovel',
              'Estate',
              'Duchy',
              'Province',
              'Colony',
              'Tunnel',
              'Cemetery',
              'Gardens',
              'Island',
              'Silk Road',
              'Farmland',
              'Duke',
              'Feodum',
              'Vineyard',
              'Fairgrounds',
              'Distant Lands',
              'Castles',
              'Humble Castle',
              'Crumbling Castle',
              'Small Castle',
              'Haunted Castle',
              'Opulent Castle',
              'Sprawling Castle',
              'Grand Castle',
              'King\'s Castle',
              'Mill',
              'Nobles',
              'Pasture',
              'Cursed Gold',
              'Goat',
              'Haunted Mirror',
              'Lucky Coin',
              'Magic Lamp',
              'Pouch',
              'Copper',
              'Silver',
              'Potion',
              'Gold',
              'Spoils',
              'Platinum',
              'Fool\'s Gold',
              'Coin of the Realm',
              'Loan',
              'Masterpiece',
              'Rocks',
              'Quarry',
              'Talisman',
              'Relic',
              'Royal Seal',
              'Treasure Trove',
              'Venture',
              'Contraband',
              'Cache',
              'Plunder',
              'Horn of Plenty',
              'Ill-Gotten Gains',
              'Counterfeit',
              'Capital',
              'Charm',
              'Crown',
              'Idol',
              'Stash',
              'Harem',
              'Hoard',
              'Diadem',
              'Bank',
              'Philosopher\'s Stone',
              'Fortune',
              'Page',
              'Treasure Hunter',
              'Warrior',
              'Hero',
              'Champion',
              'Peasant',
              'Soldier',
              'Fugitive',
              'Disciple',
              'Teacher',
              'Transmute',
              'Bag of Gold',
              'Followers',
              'Princess',
              'Trusty Steed',
              'Ruins',
              'Madman',
              'Mercenary',
              'City Quarter',
              'Engineer',
              'Overlord',
              'Royal Blacksmith',
              "Will-o'-wisp",
              'Wish',
              'Necropolis',
              'Poor House',
              'Cellar',
              'Chapel',
              'Moat',
              'Courtyard',
              'Lurker',
              'Pawn',
              'Embargo',
              'Haven',
              'Lighthouse',
              'Native Village',
              'Pearl Diver',
              'Apothecary',
              'Herbalist',
              'Scrying Pool',
              'University',
              'Hamlet',
              'Crossroads',
              'Duchess',
              'Beggar',
              'Squire',
              'Vagrant',
              'Candlestick Maker',
              'Stonemason',
              'Ratcatcher',
              'Raze',
              'Encampment',
              'Patrician',
              'Settlers',
              'Druid',
              'Faithful Hound',
              'Guardian',
              'Monastery',
              'Pixie',
              'Tracker',
              'Imp',
              'Harbinger',
              'Merchant',
              'Vassal',
              'Village',
              'Workshop',
              'Masquerade',
              'Shanty Town',
              'Steward',
              'Swindler',
              'Wishing Well',
              'Ambassador',
              'Fishing Village',
              'Lookout',
              'Smugglers',
              'Warehouse',
              'Alchemist',
              'Familiar',
              'Trade Route',
              'Watchtower',
              'Fortune Teller',
              'Menagerie',
              'Develop',
              'Oasis',
              'Oracle',
              'Scheme',
              'Forager',
              'Hermit',
              'Market Square',
              'Sage',
              'Storeroom',
              'Urchin',
              'Doctor',
              'Amulet',
              'Caravan Guard',
              'Dungeon',
              'Gear',
              'Guide',
              'Catapult',
              'Gladiator',
              'Chariot Race',
              'Enchantress',
              "Farmers' Market",
              'Changeling',
              'Fool',
              'Ghost Town',
              'Leprechaun',
              'Night Watchman',
              'Secret Cave',
              'Zombie Apprentice',
              'Zombie Mason',
              'Zombie Spy',
              'Black Market',
              'Bureaucrat',
              'Militia',
              'Moneylender',
              'Poacher',
              'Remodel',
              'Smithy',
              'Throne Room',
              'Conspirator',
              'Baron',
              'Bridge',
              'Diplomat',
              'Ironworks',
              'Mining Village',
              'Secret Passage',
              'Caravan',
              'Cutpurse',
              'Navigator',
              'Pirate Ship',
              'Salvager',
              'Sea Hag',
              'Treasure Map',
              'Golem',
              'Bishop',
              'Monument', "Worker's Village",
              'Farming Village',
              'Horse Traders',
              'Remake',
              'Tournament',
              'Young Witch',
              'Jack of All Trades',
              'Noble Brigand',
              'Nomad Camp',
              'Spice Merchant',
              'Trader',
              'Armory',
              'Death Cart',
              'Fortress',
              'Ironmonger',
              'Marauder',
              'Procession',
              'Rats',
              'Scavenger',
              'Wandering Minstrel',
              'Advisor',
              'Herald',
              'Plaza',
              'Taxman',
              'Duplicate',
              'Magpie',
              'Messenger',
              'Miser',
              'Port',
              'Ranger',
              'Transmogrify',
              'Sacrifice',
              'Temple',
              'Villa',
              'Bard',
              'Blessed Village',
              'Conclave',
              "Devil's Workshop",
              'Exorcist',
              'Ghost',
              'Necromancer',
              'Shepherd',
              'Skulk',
              'Sauna',
              'Envoy',
              'Walled Village',
              'Dismantle',
              'Bandit',
              'Council Room',
              'Festival',
              'Laboratory',
              'Library',
              'Market',
              'Mine',
              'Sentry',
              'Witch',
              'Courtier',
              'Minion',
              'Patrol',
              'Replace',
              'Torturer',
              'Trading Post',
              'Upgrade',
              'Bazaar',
              'Explorer',
              'Ghost Ship',
              'Merchant Ship',
              'Outpost',
              'Tactician',
              'Treasury',
              'Wharf',
              'Apprentice',
              'Counting House',
              'City',
              'Mint',
              'Mountebank',
              'Rabble',
              'Vault',
              'Harvest',
              'Hunting Party',
              'Jester',
              'Cartographer',
              'Embassy',
              'Haggler',
              'Highway',
              'Inn',
              'Mandarin',
              'Margrave',
              'Stables',
              'Knights',
              'Band of Misfits',
              'Bandit Camp',
              'Catacombs',
              'Count',
              'Cultist',
              'Graverobber',
              'Junk Dealer',
              'Mystic',
              'Pillage',
              'Rebuild',
              'Rogue',
              'Dame Anna',
              'Dame Josephine',
              'Dame Molly',
              'Dame Natalie',
              'Dame Sylvia',
              'Sir Bailey',
              'Sir Destry',
              'Sir Martin',
              'Sir Michael',
              'Sir Vander',
              'Baker',
              'Butcher',
              'Journeyman',
              'Merchant Guild',
              'Soothsayer',
              'Artificer',
              'Bridge Troll',
              'Giant',
              'Haunted Woods',
              'Lost City',
              'Royal Carriage',
              'Storyteller',
              'Swamp Hag',
              'Wine Merchant',
              'Emporium',
              'Bustling Village',
              'Archive',
              'Crown',
              'Forum',
              'Groundskeeper',
              'Legionary',
              'Wild Hunt',
              'Cobbler',
              'Crypt',
              'Cursed Village',
              'Den Of Sin',
              'Pooka',
              'Sacred Grove',
              'Tormentor',
              'Tragic Hero',
              'Werewolf',
              'Vampire',
              'Bats',
              'Avanto',
              'Governor',
              'Artisan',
              'Possession',
              'Grand Market',
              'Goons',
              'Border Village',
              'Altar',
              'Hunting Grounds',
              'Hireling',
              'Raider',
              'Expand',
              'Forge', "King's Court",
              'Peddler',
              'Prince',
              'Debt',
              'debt',
              "The Earth's Gift"]
